### ISSUE TITLE
Double check the math on the error status reporting

### ISSUE THREAD

**Issue by OopsAllErrors** [NASA-IMPACT/hls-status#30]
![image](https://github.com/NASA-IMPACT/hls-status/assets/48385103/ee03feb4-7ef4-4667-8729-92565e2984b8)

I've noticed a couple instance where the math for error calculation seems to be off. For instance, you can't see in the screenshot but currently the metric shows ~19,000 started jobs and ~3,000 failed jobs, a failure rate of roughly 15%. But the text reports a failure rate more than 20%. I've seen a similar instance around the yellow status. Is the math right for this?

**Comment by rajdangol0077** [comment]
The issue seems to be due to mismatch in the sampling time for the metrics, I have made them have the same sampling time for now, and the issue seems to be resolved.
